Fixed sortable
flagrow/mason pull request #15
Opened 2020-03-29 14:17 UTC by cpascu

Fixed the sortable issue by implementing html5sortable like you requested in the extension thread.

I also changed the admin route because the old nested route wasn't updating the address bar url.

2020-03-30 08:53 UTC, ameenpv commented
Hey @cpascu , I tried using your commits in my current project. But the extension is still incompatible. Its not showing these fields to public. Is there anything I am missing out?

2020-03-30 11:06 UTC, ameenpv commented
Great.
One question, are you able to see the fields on mobile view? (Is this extension responsive enough?)

2020-03-30 11:14 UTC, clarkwinkelmann commented
@ameenpv please do not hijack unrelated threads. Check the configuration of your "See fields on all existing discussions" permission and open a new issue if that permission doesn't work as intended.

2020-03-30 11:28 UTC, ameenpv commented
@clarkwinkelmann Really sorry for that. I didn't see that configuration in first place.

2020-04-24 22:52 UTC, clarkwinkelmann requested changes
Thanks for your contribution! I haven't been able to test the PR on my own computer yet, but here are a few things I noticed while reviewing your code.

I'll try to do a test of the PR when I find some time, or maybe another FoF member will want to take care of it.

2020-04-24 22:52 UTC, clarkwinkelmann commented on js/src/admin/components/FieldAnswersEdit.js
> +        let self = this;
You should use an arrow function below so that `this` can be accessed without needing a temporary variable

2020-04-24 22:52 UTC, clarkwinkelmann commented on js/package.json
> +    "devDependencies": {
Why did one of the dependencies end up in `devDependencies` ?

2020-07-31 16:36 UTC, clarkwinkelmann commented
Fixed in b80b2edf53329069179dc4eef8863609b5fd316b

2020-07-31 16:36 UTC, closed without merging