Update for 1.0
flagrow/mason pull request #27
Opened 2021-06-05 14:56 UTC by davwheat

Updates Mason for Stable 1.0

**Main changes:**
- Fixed breaking changes
- Add missing prettier config based on the settings used during creation of the ext
- Update deps
- Add JS typings and TS support

2021-06-05 22:28 UTC, imorland requested changes
Not tested locally yet, but one small thing springs to mind..

https://github.com/FriendsOfFlarum/mason/blob/02bded3794e38b1525fa9c35b880051728e1e878/composer.json#L34
 `discussion` should be changed to `feature`

https://github.com/FriendsOfFlarum/mason/blob/02bded3794e38b1525fa9c35b880051728e1e878/src/ForumAttributes.php#L17
`app()` should now be `resolve()`

https://github.com/FriendsOfFlarum/mason/blob/02bded3794e38b1525fa9c35b880051728e1e878/src/LoadForumFieldsRelationship.php#L22

`app()` -> `resolve()`

https://github.com/FriendsOfFlarum/mason/blob/02bded3794e38b1525fa9c35b880051728e1e878/src/Api/Controllers/AnswerDeleteController.php#L21

`RequestUtil::getActor($request)->assertAdmin()`

2021-06-05 22:35 UTC, davwheat commented
Should app be replaced in the migration, too? I guess so.

2021-06-05 22:36 UTC, imorland commented
Yeah.. not for that far yet :P

2021-06-06 20:39 UTC, imorland approved these changes

2021-06-06 20:40 UTC, merged